build.gradle
src/main/groovy/ca/cutterslade/gradle/analyze/ProjectDependencyResolver.groovy

Multiproject builds often have many projects depending on the same artifact, in those cases, the plugin would inspect such jars many times, this change caches the results for the duration of a build

Added a cache of jar/classes relationship

---

README.md

Added the "test class dependencies" to the example task configuration to make it more clear that both would need to be configured (and easier for future users to copy/paste).
There is also one slightly inaccurate related statement in the readme, but I'm not sure how best to rephrase it.  "Each task can be configured to log a warning about dependency issues" is not quite accurate, as only the "analyzeClassesDependencies" and "analyzeTestClassesDependencies" tasks can be configured thusly; "analyzeDependencies" cannot.

Enhanced README example task configuration.

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPlugin.groovy
src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesTask.groovy
src/main/groovy/ca/cutterslade/gradle/analyze/ProjectDependencyResolver.groovy

Gradle 4.0 added a classes directory for each compile task/JVM language.  This requires scanning possibly several classes directories.
Support remains for gradle 2 & 3 and Java version 6 and up.

Added support for Gradle 4.0

---

README.md
build.gradle
src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPlugin.groovy
src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesTask.groovy
src/main/groovy/ca/cutterslade/gradle/analyze/ProjectDependencyResolver.groovy

This required a handful of changes, and a minor compatibility breakage.
Compatibility breaking change: The plugin must now be applied to the root project of a multi-project build.
Other changes:
* Plugin now does not fail the build when applied to a project without the java plugin applied; it has no effect on projects without the java plugin applied.
* Plugin will cause the build to fail if it has been applied to a child project but not the parent project
* Plugin now produces an output file at `"$project.buildDir/dependency-analyze/result` containing exception message which caused to build to fail. This will be an empty file if no issues were found.
* Plugin can be considered up-to-date if no input/output changes have occurred.
* Plugin output can be cached in gradle versions which …

Use gradle task output cache instead of internal static cache

---

.travis.yml

The travis CI build with OpenJDK6 is failing to download the gradle dist. I plan on abandoning Java 6 soon anyway.

Remove travis build with Java 6

---

src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPlugin.groovy

Currently this plugin does not work when you do:
```
apply plugin: 'ca.cutterslade.analyze'
apply plugin: 'java'
```
This fix will allow the above scenario to work just the same as:
```
apply plugin: 'java'
apply plugin: 'ca.cutterslade.analyze'
```

Apply tasks when 'java' is applied, not if.

---

.circleci/config.yml
README.md
build.gradle
gradle/wrapper/gradle-wrapper.properties

Bumps minimum Java version to 8; adds support for 9, 10, 11.

Upgrade dependency analyzer to 1.10

---

build.gradle

This PR updates the maven-dependency-analyzer to 1.10. It requires a newer version of Java (I have tested against 1.8) otherwise it fails on java class compiled error. 
Was there any specific reason to remain on 1.6 for this project?

Maven dependency analyzer update to 1.10

---

src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPlugin.groovy

In certain circumstances involving multi project builds, the analyze tasks would run before JARs which it requires are built. Adding a dependency on the compile configuration to the `analyzeClassesDependencies` task (and similar for test task) resolves this situation.

Make tasks depend on appropriate configuration

---

src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPlugin.groovy

Adding support for gradle 5 configurations used to declare dependencies.
According to gradle documentation https://docs.gradle.org/current/userguide/java_library_plugin.html , 
base gradle tasks like implementation, testImplementation and etc. inherited from configuration compileClasspath, runtimeClasspath, testCompileClasspath & testRuntimeClasspath.
So we should look for dependencies at gradle root configurations(compileClasspath, runtimeClasspath, testCompileClasspath & testRuntimeClasspath).
It should fix issues: https://github.com/wfhartford/gradle-dependency-analyze/issues/90 https://github.com/wfhartford/gradle-dependency-analyze/issues/39

feat(gradle-dependency-analyze): added resolvable gradle configurations to root

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesTask.groovy
src/main/groovy/ca/cutterslade/gradle/analyze/ProjectDependencyResolver.groovy

I don't know the reason for removing the analysis from artefacts which are not JAR files. I have removed it and it worked like a charm. I have also switched to a more recent version of Gradle as for me the build is working fine. 
Concerning the removal of the check of Java8, I could revert it if you can explain to me why it was introduced? I am building with Java11 with no issues.

#100: Missing support for multi-project dependencies

---

gradle/wrapper/gradle-wrapper.properties

Update Gradle Wrapper from 6.8.1 to 6.8.2.
Read the release notes: https://docs.gradle.org/6.8.2/release-notes.html
---
The checksums of the Wrapper JAR and the distribution binary have been successfully verified.
- Gradle release: `6.8.2`
- Distribution (-all) zip checksum: `1433372d903ffba27496f8d5af24265310d2da0d78bf6b4e5138831d4fe066e9`
- Wrapper JAR Checksum: `e996d452d2645e70c01c11143ca2d3742734a28da2bf61f25c82bdc288c9e637`
You can find the reference checksum values at https://gradle.org/release-checksums/
---
🤖 This PR has been created by the [Update Gradle Wrapper](https://github.com/gradle-update/update-gradle-wrapper-action) action.
<details>
<summary>Need help? 🤔</summary>
<br />
If something doesn't look right with this PR please file an issue …

Update Gradle Wrapper from 6.8.1 to 6.8.2

---

gradle/wrapper/gradle-wrapper.properties

Update Gradle Wrapper from 6.8.2 to 6.8.3.
Read the release notes: https://docs.gradle.org/6.8.3/release-notes.html
---
The checksums of the Wrapper JAR and the distribution binary have been successfully verified.
- Gradle release: `6.8.3`
- Distribution (-all) zip checksum: `9af5c8e7e2cd1a3b0f694a4ac262b9f38c75262e74a9e8b5101af302a6beadd7`
- Wrapper JAR Checksum: `e996d452d2645e70c01c11143ca2d3742734a28da2bf61f25c82bdc288c9e637`
You can find the reference checksum values at https://gradle.org/release-checksums/
---
🤖 This PR has been created by the [Update Gradle Wrapper](https://github.com/gradle-update/update-gradle-wrapper-action) action.
<details>
<summary>Need help? 🤔</summary>
<br />
If something doesn't look right with this PR please file an issue …

Update Gradle Wrapper from 6.8.2 to 6.8.3

---

src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPlugin.groovy
src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginPermitSpec.groovy

configurations were added after the evaluation of the project. So now creating the configurations
earlier when the plugin is applied.
Fixes: #153

Non SourceSet related configurations were missing

---

README.md

Starting with version 1.4.1, builds using Gradle 4.x can no longer use
this plugin and need to upgrade to Gradle 5.x. Document this so that
people who want to use this plugin can choose the appropriate version
based on the version of Gradle that they are using.
See #111

Document minimum version of Gradle required

---

README.md
src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPlugin.groovy
src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesTask.groovy
src/main/groovy/ca/cutterslade/gradle/analyze/ProjectDependencyResolver.groovy
src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginAggregatorSpec.groovy
src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginBaseSpec.groovy
src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginGradleSpec.groovy
src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginJavaTestFixturesSpec.groovy
src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginSpec.groovy

By defining a list of aggregator dependencies for the task the following will now happen:
- when an aggregator dependency includes a previously used but undeclared dependency it will be removed from the used and undeclared list and also added to the used declared list
- when an aggregator dependency does not contain any dependencies that are used it will be added to the unused declared dependency list
in that way, it Is possible to define something like a spring-boot-starter dependency as an aggregator dependency which will be used to "clean up" the result
Closes #122

Allow defining aggregator dependencies in configuration

---

README.md
src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesTask.groovy
src/main/groovy/ca/cutterslade/gradle/analyze/ProjectDependencyResolver.groovy

For large projects logging to the Gradle logger can cause OutOfMemory
exceptions to occur. Output in excess of 3MiB has been observed.
I added a flag to AnalyzeDependenciesTask called logDependencyInformationToFiles. When that flag is set to true all output is logged into files under build/analyze-dependencies/ instead of to logger.info.

Add log to file option

---

README.md
src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginBaseSpec.groovy
src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginConstantsSpec.groovy
src/test/groovy/ca/cutterslade/gradle/analyze/helper/GradleProject.groovy
src/test/groovy/ca/cutterslade/gradle/analyze/helper/GroovyClass.groovy

Clarify the capability for detecting constants when used across different gradle subprojects, as the may get inlined so that only an import is present in the resulting class file or in case of annotations using a constant from a different gradle subproject the are getting completely erased in the resulting byte code which lead to a unusedDeclaredDependency failure
closes #170

Adding a test to verify current state of constant detection capability

---

src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPlugin.groovy
src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginGradleSpec.groovy

only show message when providedRuntime configuration is present and if so it contains a dependency
Closes #220

fix message about broken Gradle war plugin

---

build.gradle
src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesTask.groovy
src/main/groovy/ca/cutterslade/gradle/analyze/ProjectDependencyResolver.groovy
src/main/groovy/ca/cutterslade/gradle/analyze/logging/AnalyzeDependenciesFileLogger.java
src/main/groovy/ca/cutterslade/gradle/analyze/logging/AnalyzeDependenciesLogger.java
src/main/groovy/ca/cutterslade/gradle/analyze/util/ProjectDependencyAnalysisResultHandler.java
src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginBaseSpec.groovy
src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginFileLoggingSpec.groovy
src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginGradleSpec.groovy
src/test/resources/analyzeClassesDependencies.log

previously `analyzeTestClassesDependencies` and `analyzeClassesDependencies` task results could override each other causing the up-to-date check to fail
fixes #229

use dedicated log files for each task
